import Head from 'next/head';
import Confetti from 'react-confetti';

import { ClientOnly } from '../components/ClientOnly';

import { useWindowSize } from '../helpers/useWindowSize';

export default function Thanks() {
  const size = useWindowSize();

  return (
    <div className="container">
      <Head>
        <title>Thank you for your submission!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1>Thanks!</h1>
        <ClientOnly>
          <Confetti width={size.width} height={size.height} />
        </ClientOnly>
      </main>
    </div>
  );
}
