import Head from 'next/head';

export default function Thanks() {
  return (
    <div className="container">
      <Head>
        <title>Thank you for your submission!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1>Thanks!</h1>
      </main>
    </div>
  );
}
